apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-banking-api
  labels:
    app: {{ .Release.Name }}-banking-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-banking-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-banking-api
    spec:
      containers:
        - name: banking-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: db-password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
