apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-banking-api-service
spec:
  selector:
    app: {{ .Release.Name }}-banking-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
