apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-api-config
  namespace: banking
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=banking;Username=banking;Password=$(DB_PASSWORD)"
  AllowedHosts: "*"
