using System.Net;
using System.Net.Http.Json;
using Lesson.Data;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Lesson.Tests;

/// <summary>
/// Lesson 06-B integration tests — Action Filters
///
/// Verifies:
///   • CorrelationIdFilter is applied globally: every response has X-Correlation-Id
///   • Client-supplied correlation ID is echoed back unchanged
///   • Auto-generated correlation ID is a valid Guid
///   • RequireBodyFilter short-circuits POST with missing body → 400
///   • RequireBodyFilter allows POST with valid body → 200
/// </summary>
public class ActionFilterTests : IClassFixture<WebApplicationFactory<Program>>, IDisposable
{
    private readonly WebApplicationFactory<Program> _factory;
    private readonly SqliteConnection _connection;
    private readonly HttpClient _client;

    public ActionFilterTests(WebApplicationFactory<Program> factory)
    {
        _connection = new SqliteConnection("DataSource=:memory:");
        _connection.Open();

        _factory = factory.WithWebHostBuilder(builder =>
            builder.ConfigureServices(services =>
            {
                var descriptor = services.SingleOrDefault(
                    d => d.ServiceType == typeof(DbContextOptions<BankingDbContext>));
                if (descriptor is not null) services.Remove(descriptor);

                services.AddDbContext<BankingDbContext>(options =>
                    options.UseSqlite(_connection));

                var sp = services.BuildServiceProvider();
                using var scope = sp.CreateScope();
                scope.ServiceProvider
                     .GetRequiredService<BankingDbContext>()
                     .Database.Migrate();
            }));

        _client = _factory.CreateClient();
    }

    public void Dispose()
    {
        _client.Dispose();
        _factory.Dispose();
        _connection.Dispose();
    }

    // ── CorrelationIdFilter — global application ───────────────────────────────

    [Fact]
    public async Task Echo_ResponseAlwaysContainsCorrelationIdHeader()
    {
        var response = await _client.GetAsync("/filters/echo");
        Assert.True(response.Headers.Contains("X-Correlation-Id"));
    }

    [Fact]
    public async Task Echo_WhenNoCorrelationIdSent_ResponseContainsAutoGeneratedGuid()
    {
        var response = await _client.GetAsync("/filters/echo");
        var value = response.Headers.GetValues("X-Correlation-Id").First();
        Assert.True(Guid.TryParse(value, out _), $"Expected a Guid but got: {value}");
    }

    [Fact]
    public async Task Echo_WhenCorrelationIdSent_SameIdIsEchoedBack()
    {
        var knownId = "test-correlation-123";
        var request = new HttpRequestMessage(HttpMethod.Get, "/filters/echo");
        request.Headers.Add("X-Correlation-Id", knownId);

        var response = await _client.SendAsync(request);

        var echoed = response.Headers.GetValues("X-Correlation-Id").First();
        Assert.Equal(knownId, echoed);
    }

    [Fact]
    public async Task AnyControllerEndpoint_AlsoReceivesCorrelationIdHeader()
    {
        // CorrelationIdFilter is global — should apply to non-filter routes too
        var response = await _client.GetAsync("/middleware/ping");
        Assert.True(response.Headers.Contains("X-Correlation-Id"));
    }

    [Fact]
    public async Task Echo_ResponseBody_ContainsCorrelationId()
    {
        var request = new HttpRequestMessage(HttpMethod.Get, "/filters/echo");
        var sentId = Guid.NewGuid().ToString();
        request.Headers.Add("X-Correlation-Id", sentId);

        var response = await _client.SendAsync(request);
        var body = await response.Content.ReadFromJsonAsync<EchoBody>();

        Assert.Equal(sentId, body?.CorrelationId);
    }

    // ── RequireBodyFilter — short-circuit on missing body ─────────────────────

    [Fact]
    public async Task BodyRequired_WhenBodyMissing_Returns400()
    {
        // POST with no body (Content-Type not set → model binding produces null)
        var response = await _client.PostAsync("/filters/body-required", null);
        Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
    }

    [Fact]
    public async Task BodyRequired_WhenBodyProvided_Returns200()
    {
        var response = await _client.PostAsJsonAsync(
            "/filters/body-required", new { value = "hello" });
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task BodyRequired_WhenBodyProvided_ResponseContainsValue()
    {
        var response = await _client.PostAsJsonAsync(
            "/filters/body-required", new { value = "world" });
        var body = await response.Content.ReadFromJsonAsync<ReceivedBody>();
        Assert.Equal("world", body?.Received);
    }

    private record EchoBody(string? CorrelationId);
    private record ReceivedBody(string? Received);
}
